document.getElementById("telefone").value = localStorage.getItem("tele") 
document.getElementById("cpf").value = localStorage.getItem("localcpf")
document.getElementById("nome").value = localStorage.getItem("localNome")
document.getElementById("email").value = localStorage.getItem("localEmail")
document.getElementById("senha").value = localStorage.getItem("localSenha")